### PR TITLE
Added accesskey to the keys

### LINKED ISSUE #8: Use accesskey to reimplement the keyboard
You can use HTML attribute `accesskey` to access the elements on the page. I've put together a small demo here: https://jsfiddle.net/x4ek56pc/

I've used jQuery in my example but that's just for the purpose of demonstration and it is not required for the `accesskey` to work.

### PR DESCRIPTION
**Pull request by gautamkrishnar**
Added accesskey to all alphabet keys and used css focus to activate key press. 

@kkuchta  Currently there's no accesskey for submit key, if you have some plans for it please let me know.

Fixes: #8 
https://html.spec.whatwg.org/multipage/interaction.html#the-accesskey-attribute
https://developer.mozilla.org/en-US/docs/Web/HTML/Global_attributes/accesskey

### CODE REVIEW

**Review by downloadpizza — COMMENTED** [review]
This seems to work, it is important to note that the combination for accesskey changes per browser. It would also be nice to have a combination for sending with keyboard (example: "-", you cant catch return with it sadly)

**Comment by gautamkrishnar** [comment]
Yes @Gabgab2003 thats why i skipped it. I was not sure whether we can use '-' for sending the data. Lets wait for @kkuchta to finalise it 😄

**Comment by Gabgab2003** [comment]
I tested again, and if you type quite fast, it gets buggy

**Comment by kkuchta** [comment]
Oh neat.  I need top play around with this!  :)

**Comment by Gabgab2003** [comment]
> 
> 
> I tested again, and if you type quite fast, it gets buggy

This is also the case if you type with buttons, so its not a specific program

**Comment by gautamkrishnar** [comment]
@kkuchta  Do you need any more changes on this PR?

**Comment by gautamkrishnar** [comment]
Closing since inactive

**Pull request closed without merging**
